AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Tarius: CFN Template to create am IAM Role for Lambda Function

Metadata:
  TemplateName: iam-role-stack.yaml
  TemplateType: IAM Role / IAM Policy
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Tarius
  Modification History:
    - 1.0.0  - Aug 30, 2023   -- Initial Version 
  Resources: 
    - IAM Role
    - IAM Policy Attached To The Role
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      Parameters: 
        - ProjectName
        - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    #################################### KMS Key ###################################################
    - Label: 
        default: 'KMS Configuration:'
      Parameters: 
      - KmsMasterKeyId
    #################################### S3 Bucket #################################################
    - Label: 
        default: 'Landing Zone S3 Bucket:'
      Parameters:
        - S3LandingZoneBucketBaseName
    #################################### Lambda Function ###########################################
    - Label:
        default: 'Lambda Function:'
      Parameters:
      - LambdaFunctionBaseName
      - LambdaExecutionRoleBaseName
      - LambdaExecutionPolicyBaseName
    #################################### DynamoDB Table ############################################
    - Label: 
        default: 'DynamoDB Configuration:'
      Parameters: 
      - DynamoDBTableBaseName
    #################################### SNS Topic #################################################
    - Label: 
        default: 'SNS Topic:'
      Parameters: 
        - SNSTopicBaseName
    ################################## SQS Queue #################################################
    - Label: 
        default: 'SQS Queue:'
      Parameters: 
        - SQSQueueBaseName
    ParameterLabels:
      ########################################### Project Name and Environment #######################
      ProjectName:
        default: 'Project Name.'
      Environment:
        default: 'Environment Name.'
      ################################## GitHub Attributes #########################################
      GitHubRef:
        default: "GitHub Ref"
      GitHubURL: 
        default: "GitHub repository URL"
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA: 
        default: "GitHub Workflow Run Number."
      GitHubRepository:
        default: "GitHub repository name."
      CiBuild:
        default: "Feature branch Ci Build"
      ################################## Lambda Function ###########################################
      LambdaFunctionBaseName:
        default: 'The Base Name Of The Lambda Function.'
      LambdaExecutionRoleBaseName: 
        default: 'Lambda Function Execution Role Name.'
      LambdaExecutionPolicyBaseName:
        default: 'Lambda Function Execution Policy Name.'
      ################################## DynamoDB Table ############################################
      DynamoDBTableBaseName: 
        default: 'DynamoDB Table Base Name.'
      ################################## SNS Topic #################################################
      SNSTopicBaseName:
        default: 'SNS Topic Base Name.'
      ################################## SQS Queue #################################################
      SQSQueueBaseName:
        default: 'SQS Queue Base Name.'
Parameters:
  ################## Project Name and Environment ##################################################
  ProjectName:
    Default: tarius
    Description: 'The Project Name.'
    Type: String
    MinLength: 4
    MaxLength: 30
    AllowedPattern: '[a-z]*'
    ConstraintDescription: 'The length should be between 5 and 30, must contain only lowercase alphabets.'
  Environment:
    Default: devl
    Description: 'The Environment Name.'
    Type: String
    AllowedValues: ['devl', 'test', 'prod']
    ConstraintDescription: 'The Environment must be devl / test or prod'
 #################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### KMS #######################################################
  KmsMasterKeyId:
    Default: "arn:aws:kms:us-east-1:237376087602:key/f7eb118d-f1d2-4d70-a046-dfada470840e"
    Description: "The KMS Key Id Used For Encryption."
    Type: String
    MinLength: 75
    MaxLength: 75
    AllowedPattern: "[a-z:/0-9-]*"
    ConstraintDescription: "The length of the KMS Key Id should be 36 and must be lowercase alphabets, numbers and dash."  
  ###################################### S3 Bucket #################################################
  S3LandingZoneBucketBaseName:
    Default: s3-bucket
    Description: 'The S3 Bucket Base Name For The Source Data. The Region And Environment Will Be Added As Suffix By The Template.'
    Type: String
    MinLength: 3
    MaxLength: 15
    AllowedPattern: '[a-z][a-z0-9-.]*'
    ConstraintDescription: 'The length should be between 3 and 15, must contain only lowercase letter,numbers,dash, dot and should start with a letter.'
  ###################################### Lambda Function ###########################################
  LambdaFunctionBaseName:
    Default: lambda-name
    Description: Lambda Function Name Base Name
    Type: String
    MinLength: 5
    MaxLength: 40
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: The length should be between 10 and 40, must contain only alphanumeric or dash.
  LambdaExecutionRoleBaseName:
    Default: lambda-role
    Description: Lambda Function Execution Role Name
    Type: String
    MinLength: 5
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: The length should be between 5 and 10, must contain only alphanumeric or dash.
  LambdaExecutionPolicyBaseName:
    Default: policy-name
    Description: Lambda Function Execution Policy Name
    Type: String
    MinLength: 5
    MaxLength: 15
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: The length should be between 5 and 15, must contain only alphanumeric or dash.
  ###################################### DynamoDB Stream ###########################################
  DynamoDBTableBaseName:
    Default: dynamo
    Description: 'The base name of the DynamoDB Table.'
    Type: String
    MinLength: 3
    MaxLength: 15
    ConstraintDescription: 'The length should be between 3 and 15, must contain only lowercase letter, number, dash and should start with a letter.'
  ###################################### SNS Topic #################################################
  SNSTopicBaseName:
    Default: 'sns'
    Description: 'The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template.'
    Type: String
    MinLength: 3
    MaxLength: 15
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: 'The length should be between 3 and 15, must contain only lowercase letter, number, dash, dot and should start with a letter.'
  ###################################### SQS Queue #################################################
  SQSQueueBaseName:
    Default: 'sqs'
    Description: 'The Base Name Of The Sns Topic. The Region And Environment Will Be Added As Suffix By The Template.'
    Type: String
    MinLength: 3
    MaxLength: 15
    AllowedPattern: '[a-z][a-z0-9-]*'
    ConstraintDescription: 'The length should be between 3 and 15, must contain only lowercase letter, number, dash, dot and should start with a letter.'
Resources:
  ###################################### Lambda Execution Role #####################################
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${LambdaExecutionRoleBaseName}-${Environment}${CiBuild}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-${LambdaExecutionPolicyBaseName}-${Environment}${CiBuild}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowCloudWatchLogStream
              Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${ProjectName}-${LambdaFunctionBaseName}-${Environment}-${AWS::Region}${CiBuild}:*'
            - Sid: AllowDynamoDBBatchWriteItem
              Effect: Allow
              Action: 
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource:
                - !Sub 'arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}-${DynamoDBTableBaseName}-${Environment}-${AWS::Region}${CiBuild}'
            - Sid: AllowSNSPublishMessage
              Effect: Allow
              Action: 
                - sns:Publish
              Resource:
                - !Sub 'arn:${AWS::Partition}:sns:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SNSTopicBaseName}-${Environment}-${AWS::Region}${CiBuild}'
            - Sid: AllowSQSSendMessage
              Effect: Allow
              Action: 
                - sqs:SendMessage
              Resource:
                - !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${ProjectName}-${SQSQueueBaseName}-${Environment}-${AWS::Region}${CiBuild}'
            - Sid: AllowReadAccessToS3Bucket
              Effect: Allow
              Action: 
                - s3:GetObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}${CiBuild}/raw-data/*'
            - Sid: AllowWriteAccessToS3Bucket
              Effect: Allow
              Action: 
                - s3:PutObject
              Resource: !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}${CiBuild}/invalid-records/*'
            - Sid: AllowKMSDecryption
              Effect: Allow
              Action: 
                - kms:Decrypt
                - kms:Encrypt
                - kms:GenerateDataKey
                - kms:GenerateDataKeyPair
              Resource:
                - !Ref KmsMasterKeyId
      Tags: 
      - Key: ProjectName
        Value: !Ref ProjectName
      - Key: EnvironmentName
        Value: !Ref Environment
      - Key: GitHubRepository
        Value: !Ref GitHubRepository
      - Key: GitHubRef
        Value: !Ref GitHubRef
      - Key: GitHubURL
        Value: !Ref GitHubURL
      - Key: GitHubWFRunNumber
        Value: !Ref GitHubWFRunNumber
      - Key: GitHubSHA
        Value: !Ref GitHubSHA
Outputs:
  LambdaExecutionRoleArn:
    Description: The Arn of the Lambda Execution Role
    Value: !GetAtt LambdaExecutionRole.Arn
