AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Project Tarius: CFN Template To Create A S3 Table Encrypted With Customer Managed KMS Key With Or Without A Folder. 

Metadata:
  TemplateName: s3-stack.yaml
  TemplateType: S3 bucket with optionally default folder
  Version: 1.0.0
  Owner: Subhamay Bhattacharyya
  ProjectName: Tarius
  Modification History:
    - 1.0.0  - Aug 30, 2023   -- Initial Version 
  Resources: 
    - S3 Bucket Encrypted With Customer Managed KMS Key.
  StepsToTest: |
    Manualy verify the Stack.
  StepsToCleanup: |
    Stack delete command

  AWS::CloudFormation::Interface:
    ParameterGroups:
    #################################### Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      Parameters: 
      - ProjectName
      - Environment
    #################################### GitHub Attributes #########################################
    - Label:
        default: "GitHub Attributes:"
      Parameters:
      - GitHubRef
      - GitHubURL
      - GitHubWFRunNumber
      - GitHubSHA
      - GitHubRepository
      - CiBuild
    ################################## KMS Key ###################################################
    - Label: 
        default: 'KMS Configuration:'
      Parameters: 
        - S3KmsMasterKeyAlias
    #################################### S3 Bucket #################################################
    - Label:
        default: 'S3 Configuration:'
      Parameters:
      - S3LandingZoneBucketBaseName
      - S3DataBucketFolder
      - S3BucketBlockPublicAcls
      - S3BucketBlockPublicPolicy
      - S3BucketIgnorePublicAcls
      - S3BucketRestrictPublicBuckets
      - S3KmsMasterKeyAlias
    #################################### S3 Bucket #################################################
    - Label: 
        default: 'Lambda IAM Role:'
      Parameters: 
      - LambdaExecutionRoleBaseName
    ParameterLabels:
      ################################## Project Name and Environment ##############################
    - Label: 
        default: 'Project And Environment:'
      ProjectName:
        default: 'Project Name.'
      Environment:
        default: 'Environment Name.'
      ################################## GitHub Attributes #########################################
    - Label: 
        default: "GitHub Attributes:"
      GitHubRef:
        default: "GitHub Ref"
      GitHubURL: 
        default: "GitHub repository URL"
      GitHubWFRunNumber:
        default: "GitHub Workflow Run Number."
      GitHubSHA: 
        default: "GitHub Workflow Run Number."
      GitHubRepository:
        default: "GitHub repository name."
      CiBuild:
        default: "Feature branch Ci Build"
      ################################## S3 Bucket #################################################
      S3LandingZoneBucketBaseName:
        default: 'S3 Bucket Base Name.'
      S3DataBucketFolder:
        default: 'The folder(s) to be created.'
      S3BucketBlockPublicAcls:
        default: 'Allow BlockPublicAcls.'
      S3BucketBlockPublicPolicy:
        default: 'Allow BlockPublicPolicy.'
      S3BucketIgnorePublicAcls:
        default: 'Allow IgnorePublicAcls.'
      S3BucketRestrictPublicBuckets:
        default: 'Allow restrictPublicBuckets'
      S3KmsMasterKeyAlias:
        default: 'The KMS Master Key Alias To Be Used For Server Side Encryption.'
      ###################################### Lambda Role ###########################################
      LambdaExecutionRoleBaseName:
        default: "Lambda Role Base Name."
Parameters:
  ###################################### Project Name and Environment ##############################
  ProjectName:
    Default: project
    Description: 'The Project Name.'
    Type: String
    MinLength: 5
    MaxLength: 30
    AllowedPattern: '[a-z]*'
    ConstraintDescription: 'The length should be between 5 and 30, must contain only lowercase alphabets.'
  Environment:
    Default: devl
    Description: 'The Environment Name.'
    Type: String
    AllowedValues: ['devl', 'test', 'prod']
    ConstraintDescription: 'The Environment must be devl / test or prod' 
  #################################### GitHub Attributes #########################################
  GitHubRef:
    Default: ref_name
    Description: "GitHub Ref Name"
    Type: String
  GitHubURL:
    Default: "https://github.com/"
    Description: "GitHub URL"
    Type: String
  GitHubWFRunNumber:
    Default: 1
    Description: "The Workfloww Run Number."
    Type: Number
  GitHubSHA:
    Default: "sha"
    Description: "The sha value of the last commit"
    Type: String
  GitHubRepository:
    Default: 001-tarius
    Description: "The GitHub Repository name."
    Type: String
    MinLength: 10
    MaxLength: 30
    AllowedPattern: "[a-z0-9-.]*"
    ConstraintDescription: "The reposiroty length should be between 10 and 30, must contain only lowercase letter,numbers,dash, dot and should start with a letter."
  CiBuild:
    Default: ""
    Description: "Ci Build of the feature branch."
    Type: String
  ###################################### KMS Key ###################################################
  S3KmsMasterKeyAlias:
    Default: 'SB-KMS'
    Description: 'The KMS Master Key Alias To Be Used For Server Side Encryption.'
    Type: String
    MinLength: 5
    MaxLength: 20
    AllowedPattern: '[a-zA-Z0-9-]*'
    ConstraintDescription: 'The length of the KMS Key Alias should be beteen 5 and 20 and can only contain lowercase alphanumeric characters and dash.'
  ###################################### S3 Bucket #################################################
  S3LandingZoneBucketBaseName:
    Default: s3-bucket
    Description: 'The S3 Bucket Base Name For The Source Data, The Region Will Be Added As Suffix By The Template.'
    Type: String
    MinLength: 3
    MaxLength: 15
    AllowedPattern: '[a-z][a-z0-9-.]*'
    ConstraintDescription: 'The length should be between 3 and 40, must contain only lowercase letter,numbers,dash, dot and should start with a letter.'
  S3DataBucketFolder:
    Default: 'raw-data'
    Description: 'The Folder To Be Created For Stroing The Raw Data. Use do_not_create If You Do Not Want To Create Any Folder.'
    Type: CommaDelimitedList
    ConstraintDescription: 'Should be a comma seperated folder names.'
  S3BucketBlockPublicAcls:
    Default: true
    Description: 'Allow Block Public Acls'
    Type: String
    AllowedValues: [true, false]
  S3BucketBlockPublicPolicy:
    Default: true
    Description: 'Allow Block Public Policy'
    Type: String
    AllowedValues: [true, false]
  S3BucketIgnorePublicAcls:
    Default: true
    Description: 'Allow Ignore Public Acls'
    Type: String
    AllowedValues: [true, false]
  S3BucketRestrictPublicBuckets:
    Default: true
    Description: 'Allow Restrict Public Buckets'
    Type: String
    AllowedValues: [true, false]
  S3CustomResourceStackName:
    Default: 'lilac-s3-cust-res-cross-stack'
    Description: 'S3 Custom Resource Stack Name'
    Type: String
  ###################################### Lambda Role ###########################################
  LambdaExecutionRoleBaseName:
    Default: lambda-role
    Description: "The Execution Role Of The Lambda Function."
    Type: String
    MinLength: 10
    MaxLength: 40
    AllowedPattern: '[a-zA-Z-]*'
    ConstraintDescription: "Must be between 5 and 255 characters long and begin with a letter and can contain number or hyphen (-)."
Resources:
  ###################################### S3 Bucket #################################################
  S3LandingZoneBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}${CiBuild}'
      BucketEncryption:
          ServerSideEncryptionConfiguration: 
          - BucketKeyEnabled: True
            ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'aws:kms'
              KMSMasterKeyID: !Sub 'alias/${S3KmsMasterKeyAlias}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: !Ref S3BucketBlockPublicAcls
        BlockPublicPolicy: !Ref S3BucketBlockPublicPolicy
        IgnorePublicAcls: !Ref S3BucketIgnorePublicAcls
        RestrictPublicBuckets: !Ref S3BucketRestrictPublicBuckets
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
        - Key:  Environment
          Value: !Ref Environment
        - Key: GitHubRepository
          Value: !Ref GitHubRepository
        - Key: GitHubRef
          Value: !Ref GitHubRef
        - Key: GitHubURL
          Value: !Ref GitHubURL
        - Key: GitHubWFRunNumber
          Value: !Ref GitHubWFRunNumber
        - Key: GitHubSHA
          Value: !Ref GitHubSHA
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3LandingZoneBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: 'allow-s3-list-bucket'
            Action:
              - s3:ListBucket
            Effect: Allow
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}${CiBuild}'
            Principal: 
              AWS: 
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/iamadmin'
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ProjectName}-${LambdaExecutionRoleBaseName}-${Environment}${CiBuild}'
          - Sid: 'allow-s3-read-write'
            Action:
              - s3:PutObject
              - s3:GetObject
            Effect: Allow
            Resource: !Sub 'arn:${AWS::Partition}:s3:::${ProjectName}-${S3LandingZoneBucketBaseName}-${Environment}-${AWS::Region}${CiBuild}/*'
            Principal: 
              AWS: 
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:user/iamadmin'
                - !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:role/${ProjectName}-${LambdaExecutionRoleBaseName}-${Environment}${CiBuild}'
  S3DataBucketCustomResource:
    Type: Custom::S3CustomResource
    Properties:
      ServiceToken: 
        Fn::ImportValue: !Sub '${S3CustomResourceStackName}-S3CreateFolderCustomResourceLambdaFunctionArn' 
      bucket_name: !Ref S3LandingZoneBucket
      folders_to_create: !Ref S3DataBucketFolder
Outputs:
  S3LandingZoneBucketArn:
    Description: The endpoint of the S3 source data bucket.
    Value: !GetAtt S3LandingZoneBucket.Arn
